<?php

namespace App\Form;

use App\Entity\Consultation;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ConsultationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('utilisateur',EntityType::class,['class'=> 'App\Entity\Utilisateur'] )
            ->add('dateDebut',DateType::class, [
                        'widget' => 'single_text'])
            ->add('dataFin',DateType::class, [
                'widget' => 'single_text'])
            ->add('description')
            ->add('refernce')
            ->add('statut')
            ->add('detailConsultations',  CollectionType::class, [
                'entry_type' => DetailConsultationType::class,
                'entry_options' => [
                    'label' => false
                ],
                'by_reference' => false,
                // this allows the creation of new forms and the prototype too
                'allow_add' => true,
                // self explanatory, this one allows the form to be removed
                'allow_delete' => true
            ])
            // just a regular save button to persist the changes
            ->add('save', SubmitType::class, [
                'attr' => [
                    'class' => 'btn btn-success'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Consultation::class,
        ]);
    }

//    public function getParent()
//    {
//        return parent::getParent(); // TODO: Change the autogenerated stub
//    }
}
